//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSec.Runtime {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>mscorlib</string>
  <string>mscorlib.resources</string>
  <string>vshost32</string>
  <string>System</string>
  <string>System.Core</string>
  <string>System.Data</string>
  <string>System.Net.Http</string>
  <string>System.Drawing</string>
  <string>System.Windows.Forms</string>
  <string>System.Xml</string>
  <string>System.Xml.Linq</string>
  <string>System.Data.DataSetExtensions</string>
  <string>Microsoft.CSharp</string>
  <string>Microsoft.VisualStudio.Debugger.Runtime</string>
  <string>Microsoft.VisualStudio.HostingProcess.Utilities</string>
  <string>Microsoft.VisualStudio.HostingProcess.Utilities.Sync</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IgnoreAssemblies {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IgnoreAssemblies"]));
            }
        }
    }
}
